### ISSUE TITLE
Test exits with non-zero exit code

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-tape-runner#1]
I've been trying to fix the build in the [fix-build](https://github.com/stryker-mutator/stryker-tape-runner/tree/fix-build) branch. There is just one problem remaining: one tests causes a non-zero exit code. This behavior can be seen [here](https://travis-ci.org/stryker-mutator/stryker-tape-runner/jobs/222574449).

The test that is causing the issue is ['Given that there are multiple failed tests, should report completed tests without errors'](https://github.com/stryker-mutator/stryker-tape-runner/blob/fix-build/test/integration/TapeTestRunnerSpec.ts#L70). Any idea what this could be @jeznag?

**Comment by jeznag** [comment]
Hmm yeah I had trouble with that as well. The issue is that tape will throw an exception for any failed tests. I thought that wrapping it inside mocha would stop that from returning a non-zero exit code but apparently it's still happening :( Will look into it.
